version: "3"

services:
  penguin:
    build:
      context: .
    container_name: penguin
    restart: always
    ports:
      - "127.0.0.1:3001:3001"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB: